name: test-macos
run-name: Run tests on ARM macOS
on:
  push:
    branches: ['master']
  pull_request:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Pull submodules
        run: git submodule update --init --recursive
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Install dependencies
        run: |
          brew install meson ninja
      - name: Build
        run: |
          meson setup build --debug --warnlevel 3 --werror -Dcpp_debugstl=true
          ninja -C build
      - name: Test
        run: |
          ninja -C build test
      - name: upload bin
        uses: actions/upload-artifact@v2
        with:
            name: build/oicompare
